sudo: required
dist: bionic
addons:
  chrome: stable
language: node_js
node_js:
- 10
install:
- npm install -g grunt-cli
- npm install -g bower
- npm install
- bower install
before_script:
- grunt build
deploy:
  skip_cleanup: true
  provider: npm
  email: mail@flexberry.net
  api_key:
    secure: gAg4hMo+qPiZQfC7NlGObRCJmis7PX/lbFP3RdBpglPznjrJVhGw5gYVMJlA/euAWwg3ki4Lc/PITFnGs+nZzXfcbaUt+HoIgSyJAbLj2amleoAMOVD5B4q/6AI/07UMShbHbs5uimYkFHRHcqXuaUllUJYiuf9WEuLkH2kiDHo=
  on:
    tags: true
