name: Check PR

on:
  pull_request:
    branches: [ develop, master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: 16

    steps:

    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node }}

    - name: Install grunt-cli and npm/bower dependencies
      run: |
        set -x
        node -v
        npm install -g grunt-cli
        npm install -g bower
        npm install
        bower install

    - name: Grunt build, karma tests
      run: |
         grunt build
         grunt test
